{{- $template := fromYaml (include "manifest.resource" .) -}}
{{- $additionalLabels := .Values.additionalLabels | default dict -}}
{{- $additionalAnnotations := .Values.additionalAnnotations | default dict -}}
{{- range .Values.resources }}
---
{{ toYaml (mergeOverwrite (dict "metadata" (dict "labels" $additionalLabels "annotations" $additionalAnnotations)) (merge . $template)) -}}
{{- end }}
{{- range $i, $t := .Values.templates }}
---
{{ toYaml (mergeOverwrite (dict "metadata" (dict "labels" $additionalLabels "annotations" $additionalAnnotations)) (merge (tpl $t $ | fromYaml) $template)) -}}
{{- end }}